In [2]:
import numpy as np 
lst = [1, 4, 5, 6, 3, 2]

# 一次性热编码
max_value = max(lst)
one_hot_encoded = np.eye(max_value)[np.array(lst)-1]  # 减1以匹配0索引数组

print(one_hot_encoded)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
